service: node-lambda
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x 
  timeout: 10
  
functions:
  lambda:
    handler: src/handler.handler
    events:
      - httpApi:
          path: /pokemonApi/getEvolutionChain/{pokemonName}
          method: get

custom:
  serverless-offline:
    httpPort: 4000
          
plugins:
  - serverless-offline

  
